Repository RAF-SI-2023/Banka-1-Infrastructure, pull requests merged in 2024-06, with the labels that each got.

#1 helm chart
  .prow/build.yaml
  helm/.gitignore
  helm/banka-1-backend/.helmignore
  helm/banka-1-backend/Chart.yaml
  helm/banka-1-backend/templates/fetching-service.yaml
  helm/banka-1-backend/templates/ingress.yaml
  helm/banka-1-backend/templates/market-service.yaml
  helm/banka-1-backend/templates/postgres.yaml
  helm/banka-1-backend/templates/redis.yaml
  helm/banka-1-backend/templates/user-service.yaml
  helm/banka-1-backend/values.yaml
  helm/banka-1-frontend/.helmignore
  helm/banka-1-frontend/Chart.yaml
  helm/banka-1-frontend/templates/frontend-service.yaml
  helm/banka-1-frontend/templates/ingress.yaml
  helm/banka-1-frontend/values.yaml
  user_service-logs.txt
Labels: size/XL

#2 run if changed
  .prow/build.yaml
Labels: size/XS

#3 Requirements change
  helm/banka-1-backend/templates/fetching-service.yaml
  helm/banka-1-backend/templates/market-service.yaml
  helm/banka-1-backend/templates/redis.yaml
  helm/banka-1-backend/templates/user-service.yaml
  helm/banka-1-frontend/templates/frontend-service.yaml
Labels: size/M

#4 Values changes
  helm/banka-1-frontend/templates/frontend-service.yaml
  helm/banka-1-frontend/values.yaml
Labels: size/XS

#5 correct logs exclude
  helm/banka-1-backend/templates/fetching-service.yaml
  helm/banka-1-backend/templates/market-service.yaml
  helm/banka-1-backend/templates/user-service.yaml
Labels: lgtm, size/XS

#6 add approvers
  OWNERS
Labels: size/XS

#7 update key
  helm/banka-1-backend/templates/user-service.yaml
Labels: approved, lgtm, size/XS
